'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NA-24_LLI-1
        '''MG-27_SLI-2
        '''AL-28_SLI-2
        '''AL-29_SLI-2
        '''S-37_SLI-2
        '''CL-38_SLI-2
        '''K-42_LLI-1
        '''CA-47_-
        '''CA-49_SLI-2
        '''SC-46_LLI-2
        '''SC-47_-
        '''TI-51_SLI-2
        '''V-52_SLI-2
        '''CR-51_LLI-2
        '''MN-54_-
        '''MN-56_SLI-2
        '''FE-59_LLI-2
        '''CO-60m_-
        '''CO-60_LLI-2
        '''CO-58_LLI-2
        '''NI-65_-
        '''CU-64_-
        '''CU-66_SLI-2
        '''ZN-65_LLI-2
        '''ZN-69m_-
        '''GA-70_-
        '''GA-72_-
        '''GE-75_-
        '''GE-77_-
        '''AS-76_LLI-1
        '''SE-75_LLI-2
        '''SE-81_-
        '''SE-81m_-
        '''BR-80_-
        '''BR-82_LLI-1
        '''RB-86_LLI-2
        '''RB-88_-
        '''SR-85_LLI-2
        '''SR-87m_-
        '''Y-90m_-
        '''ZR-95_LLI-2
        '''NB-94m_-
        '''MO-99_LLI-1
        '''MO-101_-
        '''RU-97_-
        '''RU-103_LLI-2
        '''RH-104m_-
        '''PD-109m_-
        '''AG-108_-
        '''AG-110m [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property table_nuclides_def() As String
            Get
                Return ResourceManager.GetString("table_nuclides_def", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
